on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
        with:
          repository: andersbea/private-reusable-action
          # token: ${{ secrets.TOKEN}} We won't use this within this example repository, as it is public for your sake
          path: reusable-actions
      - name: Run reusable workflow
        uses: ./reusable-actions/hello-world
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
